# Generated by Django 2.1.7 on 2022-09-09 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220909_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 9, 12, 46, 24, 938899)),
        ),
    ]
